server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/product_db
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # RabbitMQ configuration
  rabbitmq:
  host=localhost
  rabbitmq.port=5672
  rabbitmq.username=guest
  rabbitmq.password=guest
  rabbitmq.exchange=order_exchange
  rabbitmq.routing-key=order_routing_key
