server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**

        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/products/**

        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**

        - id: customer-service
          uri: http://localhost:8084
          predicates:
            - Path=/customers/**

        - id: notification-service
          uri: http://localhost:8085
          predicates:
            - Path=/notifications/**
